# Generated by Django 5.1.7 on 2025-03-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_app', '0002_userstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='current_cycle_used',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_latitude',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_longitude',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pickup_longitude',
        ),
        migrations.AddField(
            model_name='trip',
            name='current_location_lat',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_location_lng',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_location_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance_from_current_pickup',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance_from_pickup_dropoff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_location_lat',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_location_lng',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_location_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration_from_current_pickup',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration_from_pickup_dropoff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location_lat',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location_lng',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location_name',
            field=models.TextField(default=''),
        ),
    ]
