# Generated by Django 5.1.7 on 2025-03-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_app', '0003_remove_trip_current_cycle_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_location_lat',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_location_lng',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location_lat',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location_lng',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location_lat',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location_lng',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
    ]
