# Generated by Django 5.1.7 on 2025-04-01 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_app', '0004_alter_trip_current_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eld_app.trip'),
        ),
    ]
