# Generated by Django 5.1.7 on 2025-04-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_app', '0006_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='latitude',
            new_name='location_lat',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='longitude',
            new_name='location_lng',
        ),
        migrations.AddField(
            model_name='logentry',
            name='activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='location_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
