# Generated by Django 5.1.7 on 2025-04-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_app', '0007_rename_timestamp_logentry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='location_lat',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='location_lng',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
