# Generated by Django 5.1.7 on 2025-04-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_app', '0008_alter_logentry_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='location_lat',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='location_lng',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_location_lat',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_location_lng',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location_lat',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location_lng',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location_lat',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location_lng',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
    ]
