# Generated by Django 5.1.7 on 2025-04-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_app', '0009_alter_logentry_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='route_distance_from_start_point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
