# Generated by Django 5.1.7 on 2025-04-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_app', '0010_logentry_route_distance_from_start_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='status',
            field=models.CharField(choices=[('Driving', 'Driving'), ('On Duty (not driving)', 'On Duty (not driving)'), ('Off Duty', 'Off Duty'), ('Sleeper Berth', 'Sleeper Berth')], max_length=50),
        ),
    ]
